version: 2
updates:
  - package-ecosystem: docker
    directory: /demo-apps/cf-extplugtest-server/service
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
